name: 🧪 Level 1 - Hello World

on:
  push:
    branches:
      - main
      - master

jobs:
  say-hello:
    name: 👋 Say Hello from GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout Repository
        uses: actions/checkout@v4

      - name: 🚀 Say Hello
        run: echo "🎉 Hello, GitHub Actions is now running CI/CD!"